/*
Please refer to readme.html for full Instructions

Text[...]=[title,text]

Style[...]=[TitleColor,TextColor,TitleBgColor,TextBgColor,TitleBgImag,TextBgImag,TitleTextAlign,TextTextAlign, TitleFontFace, TextFontFace, TipPosition, StickyStyle, TitleFontSize, TextFontSize, Width, Height, BorderSize, PadTextArea, CoordinateX , CoordinateY, TransitionNumber, TransitionDuration, TransparencyLevel ,ShadowType, ShadowColor]
*/

var FiltersEnabled = 1 // if your not going to use transitions or filters in any of the tips set this to 0

Text[0]=["<p style='margin-bottom:1px;'>Button Types</p>","<div style='float: left;'><img src='../../images/wpfinfoimg.jpg' hspace='5' /></div><div style='margin-bottom:5px;'>There are three different categories of buttons offered in the Buttons control suite - Regular, Repeat and Toggle - with multiple styles within each category. Whether it's changing colors, borders or opacity, creating a unique appearance for each Button is as simple as using the Properties feature.</div><div style='margin-bottom:5px;'>A Regular Button is a control which fires an event each time it is pressed and released such as Start/Stop. Styles include Generic (round or square), Gel, Industrial Push Button, Navigate Generic, and Navigate Gel.</div><div style='margin-bottom:5px;'> A Repeat Button is a control which repeatedly fires an event from the time it is pressed until it is released. Choose from Generic Repeat (round or square), and Gel Repeat.</div><div style='margin-bottom:5px;'>A Toggle Button is a control which turns an event On/Off or display can display a True/False reading. Clicking the button toggles between the two button states. Styles include Generic toggle (round or square), Power, Toggle Switch, Industrial Toggle, Flat Toggle, and Gel Toggle.</div>"]
Text[1]=["<p style='margin-bottom:1px;'>Fan Types</p>","<div style='float: left;'><img src='../../images/wpfinfoimg.jpg' hspace='5' /></div><div style='margin-bottom:5px;'>A Fan control displays the relative speed of rotation by the rotating fan blades.  Fans can be used as independent controls or added to a motor for a more realistic representation.</div><div>The user has the option of adjusting speed and power in addition to many other customizable properties.  Fan styles include Simple, Multi-Blade, and Wind Generator.</div>"]
Text[2]=["<p style='margin-bottom:1px;'>Linear Gauge Types</p>","<div style='float: left;'><img src='../../images/wpfinfoimg.jpg' hspace='5' /></div><div style='margin-bottom:5px;'>The Linear gauge is a data-bound control that shows the user a graduated numerical value in an easy-to-read visual presentation.  A typical linear gauge representation would be a thermometer, but could also be used to represent the readout on a tire pressure gauge.</div>Since the range of our Generic, Horizontal, and Pointy Linear gauges can be set by the user using an infinite set of numbers, they can represent whatever is needed.  Linear gauges can be horizontally or vertically oriented.   "]
Text[3]=["<p style='margin-bottom:1px;'>Motor Types</p>","<div style='float: left;'><img src='../../images/wpfinfoimg.jpg' hspace='5' /></div><div style='margin-bottom:5px;'>Motors provide a graphic illustration of how fast a motor is running by showing an indicator brush in the control.  The speed of the motor is user-controlled - the faster the indicator moves, the faster the motor is running.</div>  By entering user-controlled properties, motor controls can be used to monitor motor behavior, life, or even scheduled maintenance intervals.  We offer Heavy Duty, Square and Cylinder motors."]
Text[4]=["<p style='margin-bottom:1px;'>Pipe Types</p>","<div style='float: left;'><img src='../../images/wpfinfoimg.jpg' hspace='5' /></div><div style='margin-bottom:5px;'>Pipe controls are used for displaying the movement of vapors or liquids.  The control contains a flow indicator graphically displaying the direction the vapor or liquid is moving.</div> Using a combination of our Standard Straight, Fitted Straight, Standard Elbow, Fitted Elbow, and Ball Joint controls makes it easy to create a custom configuration."]
Text[5]=["<p style='margin-bottom:1px;'>Radial Gauge Types</p>","<div style='float: left;'><img src='../../images/wpfinfoimg.jpg' hspace='5' /></div><div style='margin-bottom:5px;'>The Radial Gauge is a data-bound control that allows the user to view quantitative information in an easy-to-understand visual format.  Round-faced gauges could be used to simulate odometers, speedometers, water level and water pressure.  Square-faced gauges could be used to simulate voltage and amperage levels.</div>  Styles offered include Racing, Square, Variable and Quarter.  Changing the name of the gauge, its incremental scale and tick values makes it easy to create a gauge to suit your needs.  "]
Text[6]=["<p style='margin-bottom:1px;'>Slider Types</p>","<div style='float: left;'><img src='../../images/wpfinfoimg.jpg' hspace='5' /></div><div style='margin-bottom:5px;'>Sliders allow the user to manipulate the value of the control graphically within a finite range.  The orientation can be horizontal or vertical with the incremental readout on one or both sides of the slider button.</div>  An example of a Slider use would be to graphically display bass or treble levels on sound studio equipment.   We offer four different styles:   Simple Fader, Spherical Slider, and Trenched."]
Text[7]=["<p style='margin-bottom:1px;'>Tank Types</p>","<div style='float: left;'><img src='../../images/wpfinfoimg.jpg' hspace='5' /></div><div style='margin-bottom:5px;'>Tanks can be used as a storage, mixing, or transporting device.  Using a fluid brush the Tank Control shows the level of a tank in proportion to the total tank capacity level.</div>  Using the properties feature it's easy to change the color of the tank and its fill.  There are five different types of tanks in the suite:  Indicator, Cutaway, Vessel, Funnel and Cylinder."]

Style[0]=["white","black","#000099","#E8E8FF","","","","","","","","","","",200,"",2,2,10,10,51,1,0,"",""]
Style[1]=["white","black","#000099","#E8E8FF","","","","","","","center","","","",200,"",2,2,10,10,"","","","",""]
Style[2]=["white","black","#000099","#E8E8FF","","","","","","","left","","","",200,"",2,2,10,10,"","","","",""]
Style[3]=["white","black","#000099","#E8E8FF","","","","","","","float","","","",200,"",2,2,10,10,"","","","",""]
Style[4]=["white","black","#000099","#E8E8FF","","","","","","","fixed","","","",200,"",2,2,1,1,"","","","",""]
Style[5]=["white","black","#000099","#E8E8FF","","","","","","","","sticky","","",200,"",2,2,10,10,"","","","",""]
Style[6]=["white","black","#000099","#E8E8FF","","","","","","","","keep","","",200,"",2,2,10,10,"","","","",""]
Style[7]=["white","black","#000099","#E8E8FF","","","","","","","","","","",200,"",2,2,40,10,"","","","",""]
Style[8]=["white","black","#000099","#E8E8FF","","","","","","","","","","",200,"",2,2,10,50,"","","","",""]
Style[9]=["white","black","#000099","#E8E8FF","","","","","","","","","","",200,"",2,2,10,10,51,0.5,75,"simple","gray"]
Style[10]=["white","black","black","white","","","right","","Impact","cursive","center","",3,5,200,150,5,20,10,0,50,1,80,"complex","gray"]
Style[11]=["white","black","#000099","#E8E8FF","","","","","","","","","","",200,"",2,2,10,10,51,0.5,45,"simple","gray"]
Style[12]=["white","black","#8b8b8b","#FFFFFF","","","","","Arial","Arial","","sticky",2,2.5,500,"",2,2,10,10,50,10,"","",""]

applyCssFilter()

