function GetString(s){var rootObject = this, parts = s.toLowerCase( ).split('.'), iCount = parts.length;for (var i = 0; i < iCount; i++){var currentPart = parts[i];rootObject = rootObject[currentPart];if (rootObject == null){return '';}}return rootObject.toString( );}
registerNamespace("live.shared.strings");
live.shared.strings.dialog_cancel ="Cancel";
live.shared.strings.dialog_insert ="Insert";
live.shared.strings.dialog_ok ="OK";
registerNamespace("live.shared.globalsettings.rte.blockmenu");
live.shared.globalsettings.rte.blockmenu.labels ="Normal,Address,Header 3,Header 2,Header 1";
live.shared.globalsettings.rte.blockmenu.values ="P,ADDRESS,H3,H2,H1";
live.shared.globalsettings.rte.bold ="B,B";
registerNamespace("live.shared.globalsettings.rte.emote");
live.shared.globalsettings.rte.emote.labels ="Smile,Open-mouthed,Wink,Surprised,Tongue out,Hot,Angry,Confused,Embarrassed,Sad,Crying,Disappointed,Angel,Baring teeth,Nerd,Sick,Party,Sleepy,Thinking,Don't tell anyone,Secret telling,Sarcastic,Eye-rolling,Red heart,Broken heart,MSN Messenger icon,Cat face,Dog face,Snail,Black Sheep,Sleeping half-moon,Star,Sun,Rainbow,Left hug,Right hug,Red lips,Red rose,Wilted rose,Clock,Gift with a bow,Birthday cake,Camera,Light bulb,Coffee cup,Telephone receiver,Mobile Phone,Auto,Airplane,Computer,Money,Filmstrip,Note,Pizza,Soccer ball,E-mail,Boy,Girl,Island with a palm tree,Umbrella";
live.shared.globalsettings.rte.emote.map ="emo.gif";
live.shared.globalsettings.rte.emote.url ="emoticons/";
registerNamespace("live.shared.globalsettings.rte.fontmenu");
live.shared.globalsettings.rte.fontmenu.fonts ="Arial,Arial Black,Comic Sans MS,Courier New,Garamond,Lucida Handwriting,Segoe UI,Times New Roman,Tahoma,Verdana";
live.shared.globalsettings.rte.imagebar ="Align Left,Default Alignment,Align Right,Align Top,Align Middle,Align Bottom";
live.shared.globalsettings.rte.italic ="I,I";
registerNamespace("live.shared.globalsettings.rte.sizemenu");
live.shared.globalsettings.rte.sizemenu.labels ="Extra Small,Small,Normal,Large,Larger,Extra Large,Largest";
registerNamespace("live.shared.globalsettings.rte.toolbar");
live.shared.globalsettings.rte.toolbar.map ="images/toolbarmap.png";
live.shared.globalsettings.rte.underline ="U,U";
registerNamespace("live.shared.marketinfo");
live.shared.marketinfo.rteformaticonfont ="Times New Roman";
live.shared.marketinfo.rteformaticonsize ="12pt";
registerNamespace("live.shared.strings.colors");
live.shared.strings.colors.clear ="Clear Colors";
live.shared.strings.colors.more ="More Colors";
registerNamespace("live.shared.strings.linkmenu");
live.shared.strings.linkmenu.delimeter =":";
live.shared.strings.linkmenu.dialoglabel ="Insert Link";
live.shared.strings.linkmenu.newwindowlabel ="Open in new window";
live.shared.strings.linkmenu.nofollow ="Prevent search engines from indexing this link";
live.shared.strings.linkmenu.textinfo ="Enter the title for the link here";
live.shared.strings.linkmenu.textlabel ="Title";
live.shared.strings.linkmenu.urlinfo ="Enter the link location here";
live.shared.strings.linkmenu.urllabel ="Link";
registerNamespace("live.shared.strings.toolbar");
live.shared.strings.toolbar.backgroundcolor ="Text Highlight Color";
live.shared.strings.toolbar.bold ="Bold";
live.shared.strings.toolbar.bulletedlist ="Bulleted List";
live.shared.strings.toolbar.copy ="Copy";
live.shared.strings.toolbar.cut ="Cut";
live.shared.strings.toolbar.decreaseindent ="Decrease Indent";
live.shared.strings.toolbar.emoticons ="Emoticons";
live.shared.strings.toolbar.html ="HTML";
live.shared.strings.toolbar.htmltip ="View HTML";
live.shared.strings.toolbar.increaseindent ="Increase Indent";
live.shared.strings.toolbar.insertline ="Insert Line";
live.shared.strings.toolbar.insertlink ="Insert Link";
live.shared.strings.toolbar.insertsearchlink ="Insert Search Link";
live.shared.strings.toolbar.italics ="Italic";
live.shared.strings.toolbar.justifycenter ="Center Justify";
live.shared.strings.toolbar.justifyleft ="Left Justify";
live.shared.strings.toolbar.justifyright ="Right Justify";
live.shared.strings.toolbar.numberedlist ="Numbered List";
live.shared.strings.toolbar.paragraph ="Paragraph size";
live.shared.strings.toolbar.paste ="Paste";
live.shared.strings.toolbar.size ="Font size";
live.shared.strings.toolbar.style ="Font style";
live.shared.strings.toolbar.textcolor ="Text Color";
live.shared.strings.toolbar.underline ="Underline";
