var smiley_smiley2image_s = new Array();
var smiley_smiley2image_r = new Array();
smiley_smiley2image_s.push('\\(bah\\)');
smiley_smiley2image_s.push('\\(brb\\)');
smiley_smiley2image_s.push('\\(ap\\)');
smiley_smiley2image_s.push('\\(au\\)');
smiley_smiley2image_s.push('\\(ci\\)');
smiley_smiley2image_s.push('\\(co\\)');
smiley_smiley2image_s.push('\\(h5\\)');
smiley_smiley2image_s.push('\\(ip\\)');
smiley_smiley2image_s.push('\\(li\\)');
smiley_smiley2image_s.push('\\(mo\\)');
smiley_smiley2image_s.push('\\(mp\\)');
smiley_smiley2image_s.push('\\(pi\\)');
smiley_smiley2image_s.push('\\(pl\\)');
smiley_smiley2image_s.push('\\(sn\\)');
smiley_smiley2image_s.push('\\(so\\)');
smiley_smiley2image_s.push('\\(st\\)');
smiley_smiley2image_s.push('\\(tu\\)');
smiley_smiley2image_s.push('\\(um\\)');
smiley_smiley2image_s.push('\\(xx\\)');
smiley_smiley2image_s.push('\\(yn\\)');
smiley_smiley2image_s.push('\\(\\|\\|\\)');
smiley_smiley2image_s.push('\\<\\:o\\)');
smiley_smiley2image_s.push('\\(#\\)');
smiley_smiley2image_s.push('\\(%\\)');
smiley_smiley2image_s.push('\\(&\\)');
smiley_smiley2image_s.push('\\(\\*\\)');
smiley_smiley2image_s.push('\\(6\\)');
smiley_smiley2image_s.push('\\(8\\)');
smiley_smiley2image_s.push('\\(\\?\\)');
smiley_smiley2image_s.push('\\(@\\)');
smiley_smiley2image_s.push('\\(A\\)');
smiley_smiley2image_s.push('\\(B\\)');
smiley_smiley2image_s.push('\\(C\\)');
smiley_smiley2image_s.push('\\(D\\)');
smiley_smiley2image_s.push('\\(E\\)');
smiley_smiley2image_s.push('\\(F\\)');
smiley_smiley2image_s.push('\\(G\\)');
smiley_smiley2image_s.push('\\(H\\)');
smiley_smiley2image_s.push('\\(I\\)');
smiley_smiley2image_s.push('\\(K\\)');
smiley_smiley2image_s.push('\\(L\\)');
smiley_smiley2image_s.push('\\(M\\)');
smiley_smiley2image_s.push('\\(N\\)');
smiley_smiley2image_s.push('\\(O\\)');
smiley_smiley2image_s.push('\\(P\\)');
smiley_smiley2image_s.push('\\(R\\)');
smiley_smiley2image_s.push('\\(S\\)');
smiley_smiley2image_s.push('\\(T\\)');
smiley_smiley2image_s.push('\\(U\\)');
smiley_smiley2image_s.push('\\(W\\)');
smiley_smiley2image_s.push('\\(X\\)');
smiley_smiley2image_s.push('\\(Y\\)');
smiley_smiley2image_s.push('\\(Z\\)');
smiley_smiley2image_s.push('\\(\\^\\)');
smiley_smiley2image_s.push('\\(a\\)');
smiley_smiley2image_s.push('\\(b\\)');
smiley_smiley2image_s.push('\\(c\\)');
smiley_smiley2image_s.push('\\(d\\)');
smiley_smiley2image_s.push('\\(e\\)');
smiley_smiley2image_s.push('\\(f\\)');
smiley_smiley2image_s.push('\\(g\\)');
smiley_smiley2image_s.push('\\(h\\)');
smiley_smiley2image_s.push('\\(i\\)');
smiley_smiley2image_s.push('\\(k\\)');
smiley_smiley2image_s.push('\\(l\\)');
smiley_smiley2image_s.push('\\(m\\)');
smiley_smiley2image_s.push('\\(n\\)');
smiley_smiley2image_s.push('\\(o\\)');
smiley_smiley2image_s.push('\\(p\\)');
smiley_smiley2image_s.push('\\(r\\)');
smiley_smiley2image_s.push('\\(t\\)');
smiley_smiley2image_s.push('\\(u\\)');
smiley_smiley2image_s.push('\\(w\\)');
smiley_smiley2image_s.push('\\(x\\)');
smiley_smiley2image_s.push('\\(y\\)');
smiley_smiley2image_s.push('\\(z\\)');
smiley_smiley2image_s.push('\\(\\{\\)');
smiley_smiley2image_s.push('\\(\\}\\)');
smiley_smiley2image_s.push('\\(~\\)');
smiley_smiley2image_s.push('\\*-\\)');
smiley_smiley2image_s.push('\\+o\\(');
smiley_smiley2image_s.push('8-\\)');
smiley_smiley2image_s.push('8-\\|');
smiley_smiley2image_s.push('8o\\|');
smiley_smiley2image_s.push('\\:\'\\(');
smiley_smiley2image_s.push('\\:-#');
smiley_smiley2image_s.push('\\:-\\$');
smiley_smiley2image_s.push('\\:-\\(');
smiley_smiley2image_s.push('\\:-\\)');
smiley_smiley2image_s.push('\\:-\\*');
smiley_smiley2image_s.push('\\:-\\<');
smiley_smiley2image_s.push('\\:-\\>');
smiley_smiley2image_s.push('\\:-@');
smiley_smiley2image_s.push('\\:-D');
smiley_smiley2image_s.push('\\:-O');
smiley_smiley2image_s.push('\\:-P');
smiley_smiley2image_s.push('\\:-S');
smiley_smiley2image_s.push('\\:-\\[');
smiley_smiley2image_s.push('\\:-d');
smiley_smiley2image_s.push('\\:-o');
smiley_smiley2image_s.push('\\:-p');
smiley_smiley2image_s.push('\\:-s');
smiley_smiley2image_s.push('\\:-\\|');
smiley_smiley2image_s.push('\\:\\^\\)');
smiley_smiley2image_s.push(';-\\)');
smiley_smiley2image_s.push('\\^o\\)');
smiley_smiley2image_s.push('\\|-\\)');
smiley_smiley2image_s.push('\\:\\$');
smiley_smiley2image_s.push('\\:\\(');
smiley_smiley2image_s.push('\\:\\)');
smiley_smiley2image_s.push('\\:\\>');
smiley_smiley2image_s.push('\\:@');
smiley_smiley2image_s.push('\\:D');
smiley_smiley2image_s.push('\\:O');
smiley_smiley2image_s.push('\\:P');
smiley_smiley2image_s.push('\\:S');
smiley_smiley2image_s.push('\\:\\[');
smiley_smiley2image_s.push('\\:d');
smiley_smiley2image_s.push('\\:o');
smiley_smiley2image_s.push('\\:p');
smiley_smiley2image_s.push('\\:s');
smiley_smiley2image_s.push('\\:\\|');
smiley_smiley2image_s.push(';\\)');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_sheep.png\' alt=\'&#40;&#98;&#97;&#104;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#98;&#97;&#104;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_brb.png\' alt=\'&#40;&#98;&#114;&#98;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#40;&#98;&#114;&#98;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_plane.png\' alt=\'&#40;&#97;&#112;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#97;&#112;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_car.png\' alt=\'&#40;&#97;&#117;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#97;&#117;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_cigarette.gif\' alt=\'&#40;&#99;&#105;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#40;&#99;&#105;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_computer.png\' alt=\'&#40;&#99;&#111;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#99;&#111;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_highfive.png\' alt=\'&#40;&#104;&#53;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#40;&#104;&#53;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_island.png\' alt=\'&#40;&#105;&#112;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#105;&#112;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_lightning.gif\' alt=\'&#40;&#108;&#105;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#40;&#108;&#105;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_coins.png\' alt=\'&#40;&#109;&#111;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#109;&#111;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_cellphone.png\' alt=\'&#40;&#109;&#112;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#109;&#112;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_pizza.png\' alt=\'&#40;&#112;&#105;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#112;&#105;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_plate.png\' alt=\'&#40;&#112;&#108;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#40;&#112;&#108;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_snail.png\' alt=\'&#40;&#115;&#110;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#115;&#110;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_soccer.png\' alt=\'&#40;&#115;&#111;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#115;&#111;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_stormy.png\' alt=\'&#40;&#115;&#116;&#41;\' class=\'wp-smiley\' width=\'20\' height=\'19\' title=\'&#40;&#115;&#116;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_turtle.png\' alt=\'&#40;&#116;&#117;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#40;&#116;&#117;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_umbrella.png\' alt=\'&#40;&#117;&#109;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#117;&#109;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_xbox.png\' alt=\'&#40;&#120;&#120;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#40;&#120;&#120;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_fingerscrossed.png\' alt=\'&#40;&#121;&#110;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#40;&#121;&#110;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_bowl.png\' alt=\'&#40;&#124;&#124;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#40;&#124;&#124;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_party.gif\' alt=\'&#60;&#58;&#111;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#60;&#58;&#111;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_sun.png\' alt=\'&#40;&#35;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#35;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_handcuffs.png\' alt=\'&#40;&#37;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#37;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_dog.png\' alt=\'&#40;&#38;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#38;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_star.png\' alt=\'&#40;&#42;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'20\' title=\'&#40;&#42;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_devil.png\' alt=\'&#40;&#54;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#54;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_note.png\' alt=\'&#40;&#56;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#56;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_question.png\' alt=\'&#40;&#63;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#63;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_cat.png\' alt=\'&#40;&#64;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#64;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_angel.png\' alt=\'&#40;&#65;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#65;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_beer.png\' alt=\'&#40;&#66;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#66;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_coffee.png\' alt=\'&#40;&#67;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#67;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_drink.png\' alt=\'&#40;&#68;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#68;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_email.png\' alt=\'&#40;&#69;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#69;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_flower.png\' alt=\'&#40;&#70;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#70;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_gift.png\' alt=\'&#40;&#71;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#71;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_hot.png\' alt=\'&#40;&#72;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#72;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_idea.png\' alt=\'&#40;&#73;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#73;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_kiss.png\' alt=\'&#40;&#75;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#75;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_heart.png\' alt=\'&#40;&#76;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#76;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_icon.png\' alt=\'&#40;&#77;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#77;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_thumbdown.png\' alt=\'&#40;&#78;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#78;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_clock.png\' alt=\'&#40;&#79;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#79;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_photo.png\' alt=\'&#40;&#80;&#41;\' class=\'wp-smiley\' width=\'22\' height=\'19\' title=\'&#40;&#80;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_rainbow.png\' alt=\'&#40;&#82;&#41;\' class=\'wp-smiley\' width=\'22\' height=\'16\' title=\'&#40;&#82;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_sleep.png\' alt=\'&#40;&#83;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#83;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_phone.png\' alt=\'&#40;&#84;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'20\' title=\'&#40;&#84;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_brheart.png\' alt=\'&#40;&#85;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#85;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_deadflower.png\' alt=\'&#40;&#87;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#87;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_girl.png\' alt=\'&#40;&#88;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#88;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_thumbup.png\' alt=\'&#40;&#89;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#89;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_boy.png\' alt=\'&#40;&#90;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#90;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_cake.gif\' alt=\'&#40;&#94;&#41;\' class=\'wp-smiley\' width=\'17\' height=\'19\' title=\'&#40;&#94;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_angel.png\' alt=\'&#40;&#97;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#97;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_beer.png\' alt=\'&#40;&#98;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#98;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_coffee.png\' alt=\'&#40;&#99;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#99;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_drink.png\' alt=\'&#40;&#100;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#100;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_email.png\' alt=\'&#40;&#101;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#101;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_flower.png\' alt=\'&#40;&#102;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#102;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_gift.png\' alt=\'&#40;&#103;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#103;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_hot.png\' alt=\'&#40;&#104;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#104;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_idea.png\' alt=\'&#40;&#105;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#105;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_kiss.png\' alt=\'&#40;&#107;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#107;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_heart.png\' alt=\'&#40;&#108;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#108;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_icon.png\' alt=\'&#40;&#109;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#109;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_thumbdown.png\' alt=\'&#40;&#110;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#110;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_clock.png\' alt=\'&#40;&#111;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#111;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_photo.png\' alt=\'&#40;&#112;&#41;\' class=\'wp-smiley\' width=\'22\' height=\'19\' title=\'&#40;&#112;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_rainbow.png\' alt=\'&#40;&#114;&#41;\' class=\'wp-smiley\' width=\'22\' height=\'16\' title=\'&#40;&#114;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_phone.png\' alt=\'&#40;&#116;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'20\' title=\'&#40;&#116;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_brheart.png\' alt=\'&#40;&#117;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#117;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_deadflower.png\' alt=\'&#40;&#119;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#119;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_girl.png\' alt=\'&#40;&#120;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#120;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_thumbup.png\' alt=\'&#40;&#121;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#121;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_boy.png\' alt=\'&#40;&#122;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#122;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_run.png\' alt=\'&#40;&#123;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#123;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_runback.png\' alt=\'&#40;&#125;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#125;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_film.png\' alt=\'&#40;&#126;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#40;&#126;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_think.gif\' alt=\'&#42;&#45;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#42;&#45;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_sick.png\' alt=\'&#43;&#111;&#40;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#43;&#111;&#40;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_eyeroll.gif\' alt=\'&#56;&#45;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#56;&#45;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_nerd.png\' alt=\'&#56;&#45;&#124;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#56;&#45;&#124;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_teeth.png\' alt=\'&#56;&#111;&#124;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#56;&#111;&#124;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_cry.gif\' alt=\'&#58;&#39;&#40;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#58;&#39;&#40;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_donttell.png\' alt=\'&#58;&#45;&#35;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#35;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_embarrassed.png\' alt=\'&#58;&#45;&#36;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#36;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_sad.png\' alt=\'&#58;&#45;&#40;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#40;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_smiley.png\' alt=\'&#58;&#45;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_secret.png\' alt=\'&#58;&#45;&#42;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#42;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_sad.png\' alt=\'&#58;&#45;&#60;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#60;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_laugh.png\' alt=\'&#58;&#45;&#62;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#62;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_angry.png\' alt=\'&#58;&#45;&#64;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#64;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_laugh.png\' alt=\'&#58;&#45;&#68;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#68;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_ooooh.png\' alt=\'&#58;&#45;&#79;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#79;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_tongue.png\' alt=\'&#58;&#45;&#80;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#80;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_weird.png\' alt=\'&#58;&#45;&#83;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#83;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_bat.gif\' alt=\'&#58;&#45;&#91;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#58;&#45;&#91;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_laugh.png\' alt=\'&#58;&#45;&#100;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#100;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_ooooh.png\' alt=\'&#58;&#45;&#111;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#111;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_tongue.png\' alt=\'&#58;&#45;&#112;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#112;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_weird.png\' alt=\'&#58;&#45;&#115;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#115;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_neutral.png\' alt=\'&#58;&#45;&#124;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#45;&#124;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_dontknow.gif\' alt=\'&#58;&#94;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#58;&#94;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_wink.gif\' alt=\'&#59;&#45;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#59;&#45;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_sarcastic.png\' alt=\'&#94;&#111;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#94;&#111;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_sleepy.gif\' alt=\'&#124;&#45;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#124;&#45;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_embarrassed.png\' alt=\'&#58;&#36;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#36;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_sad.png\' alt=\'&#58;&#40;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#40;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_smiley.png\' alt=\'&#58;&#41;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#41;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_laugh.png\' alt=\'&#58;&#62;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#62;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_angry.png\' alt=\'&#58;&#64;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#64;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_laugh.png\' alt=\'&#58;&#68;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#68;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_ooooh.png\' alt=\'&#58;&#79;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#79;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_tongue.png\' alt=\'&#58;&#80;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#80;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_weird.png\' alt=\'&#58;&#83;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#83;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_bat.gif\' alt=\'&#58;&#91;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#58;&#91;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_laugh.png\' alt=\'&#58;&#100;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#100;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_ooooh.png\' alt=\'&#58;&#111;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#111;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_tongue.png\' alt=\'&#58;&#112;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#112;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_weird.png\' alt=\'&#58;&#115;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#115;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_neutral.png\' alt=\'&#58;&#124;\' class=\'wp-smiley\' width=\'21\' height=\'21\' title=\'&#58;&#124;\' />');
smiley_smiley2image_r.push('<img src=\'/smilies/msn_wink.gif\' alt=\'&#59;&#41;\' class=\'wp-smiley\' width=\'19\' height=\'19\' title=\'&#59;&#41;\' />');
		function smiley_convert_text(text) {
			var i;
			var smiley;
			var replacement;
			var re = new RegExp("", "i");
			for (i=0; i < smiley_smiley2image_s.length; i++) {
				smiley = smiley_smiley2image_s[i];
				replacement = smiley_smiley2image_r[i];
				// smiley = smiley.replace(/([^a-zA-Z0-9])/gi, "\\$1"); // escape everything
				re.compile(smiley, "gi");
				text = text.replace(re, replacement);
			}
			return text;
		}
		
		function toggleMoreIcons(e) {
			var moreIconsDiv = document.getElementById('moreIcons');
			var isVisible = (moreIconsDiv.style.display == 'inline');
			if (isVisible) {
				moreIconsDiv.style.display = 'none';
				e.innerHTML = 'more&nbsp;&raquo;';
			} else {
				moreIconsDiv.style.display = 'inline';
				e.innerHTML = '&laquo;&nbsp;less';
			}
		}
		
		function appendTextToComment(text) {
			var commentArea = document.getElementById('comment');
			commentArea.value = commentArea.value + text;
			ReloadTextDiv();		}
	