document.write("");
document.write("	<style>");
document.write("		#CommonBadge");
document.write("		{");
document.write("			margin: 0px;");
document.write("			border: solid 1px #cccccc;	");
document.write("			width: 180px;");
document.write("			overflow: hidden;");
document.write("			font-family: Tahoma, Arial, Helvetica;");
document.write("			font-size: 10pt;");
document.write("			color: #000000;");
document.write("		}");
document.write("		");
document.write("		#CommonBadge a:link, #CommonBadge a:visited, #CommonBadge a:hover, #CommonBadge a:active");
document.write("		{");
document.write("			color: #000000;");
document.write("		}");
document.write("");
document.write("		.CommonBadgeHeader");
document.write("		{");
document.write("			padding: 6px;");
document.write("			padding-left: 8px;");
document.write("			border-bottom: solid 1px #cccccc;");
document.write("			background-color: #e2eecd;");
document.write("			font-size: 90%;");
document.write("			font-weight: bold;");
document.write("			margin: 0px;");
document.write("			text-align: center;");
document.write("		}");
document.write("");
document.write("		.CommonBadgeContent");
document.write("		{");
document.write("			background-color: #eeeeee;");
document.write("			padding: 8px;");
document.write("		}");
document.write("");
document.write("		UL.CommonBadgeContentList");
document.write("		{");
document.write("			margin: 0px;");
document.write("			padding: 0px;");
document.write("			list-style-type: none;	");
document.write("			padding-left: 4px;");
document.write("		}");
document.write("");
document.write("		UL.CommonBadgeContentList LI");
document.write("		{");
document.write("			margin: 4px;");
document.write("			margin-left: 2px;");
document.write("			margin-right: 10px;");
document.write("			font-size: 90%;");
document.write("			text-align: center;");
document.write("		}");
document.write("");
document.write("		.CommonBadgeUserName");
document.write("		{");
document.write("			font-weight: bold;");
document.write("		}");
document.write("");
document.write("		.CommonBadgeAvatar");
document.write("		{");
document.write("		}");
document.write("");
document.write("		.CommonBadgeFooter");
document.write("		{");
document.write("			margin-top: 10px;");
document.write("			font-size: 70%;");
document.write("			text-align: center;");
document.write("		}");
document.write("	</style>");
document.write("");
document.write("	<div id=\"CommonBadge\">");
document.write("		<h4 class=\"CommonBadgeHeader\">");
document.write("			<a id=\"SiteLink\" href=\"http://www.slodug.si/\" target=\"_top\">SLODUG</a>");
document.write("		</h4>");
document.write("		<div class=\"CommonBadgeContent\">");
document.write("			<ul class=\"CommonBadgeContentList\">");
document.write("				<li class=\"CommonBadgeUserName\">");
document.write("					<a id=\"Username\" href=\"http://www.codezone-si.info/members/AndrejT.aspx\" target=\"_top\">AndrejT</a>");
document.write("				</li>");
document.write("				<li class=\"CommonBadgeAvatar\">");
document.write("					<img src=\"http://www.codezone-si.info/users/avatar.aspx?userid=2104\" border=\"1\" />");
document.write("				</li>");
document.write("				<li>");
document.write("					<img title=\"Med prvih 10 po prispevkih\" alt=\"Med prvih 10 po prispevkih\" src=\"http://www.codezone-si.info/Themes/default/images/rankicons/rankTop10.gif\" /><br /><img title=\"Moški\" alt=\"Moški\" src=\"http://www.codezone-si.info/Themes/default/images/rankicons/GenderMale.gif\" />");
document.write("				</li>");
document.write("				<li>");
document.write("					Pridružen dne 12-19-2005");
document.write("				</li>");
document.write("				<li>");
document.write("					Ljubljana, Slovenia");
document.write("				</li>");
document.write("				<li>");
document.write("					<a href=\"http://www.codezone-si.info/search/SearchResults.aspx?u=2104&o=DateDescending\" target=\"_top\">C#</a>");
document.write("				</li>");
document.write("				<li>");
document.write("					");
document.write("				</li>");
document.write("				<li>");
document.write("					 <a href=\"http://www.codezone-si.info/user/Members.aspx?search=1&r=28270f1f-ff49-451a-9c67-d1205ed7acfb\" target=\"_top\"><img src=\"http://www.codezone-si.info/utility/roleicons/28270f1f-ff49-451a-9c67-d1205ed7acfb.gif\" alt=\"SlodugTeam\" border=\"0\" /></a>");
document.write("				</li>");
document.write("			</ul>						");
document.write("			<div id=\"Footer\" class=\"CommonBadgeFooter\">");
document.write("				<span>Powered By</span>");
document.write("				<a href=\"http://communityserver.org/r.ashx?B\" target=\"_top\">Community Server</a>");
document.write("			</div>");
document.write("		</div>");
document.write("	</div>");
document.write("");
document.write("");
document.write("");
document.write("");
